export { default as AlertaConfirmacionBorrado } from './SwalAlert'
export { default as GridDiv } from './GridDiv'
export { default as EditButton } from './EditButton'
export { default as EditRedirectButton } from './EditRedirectButton'
export { default as DeleteButton } from './DeleteButton'
export { default as StyledInput } from './StyledInput'
export { default as SubmitButton } from './SubmitButton'
export { default as Formulario } from './Formulario'